language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
script: npm run build
deploy:
  provider: pages
  github_token: $github_token
  skip-cleanup: true
  local-dir: /dist
  target_branch: gh-pages
  on:
    branch: main
